export default {
  FETCH_RESOURCES: 'FETCH_RESOURCES',
  FETCH_CHARACTERS: 'FETCH_CHARACTERS',
  FETCH_CHARACTER: 'FETCH_CHARACTER',
  FETCH_PLANETS: 'FETCH_PLANETS',
  FETCH_PLANET: 'FETCH_PLANET',
  FETCH_STARSHIPS: 'FETCH_STARSHIPS',
  FETCH_STARSHIP: 'FETCH_STARSHIP',
};
