export default {
  RENDER_CHARACTERS: 'RENDER_CHARACTERS',
  RENDER_CHARACTER: 'RENDER_CHARACTER',
  RENDER_PLANETS: 'RENDER_PLANETS',
  RENDER_PLANET: 'RENDER_PLANET',
  RENDER_STARSHIPS: 'RENDER_STARSHIPS',
  RENDER_STARSHIP: 'RENDER_STARSHIP',
};
